// ==============================================
// VisualTrigger.cs - Quiz-Trigger Objekt
// ==============================================
// Loest Quick-Quiz aus wenn Spieler durchfaehrt.

using UnityEngine;

namespace BreakpilotDrive
{
    public class VisualTrigger : MonoBehaviour
    {
        [Header("Trigger-Konfiguration")]
        [SerializeField] private string triggerType = "bridge"; // "bridge", "tree", "house"

        public string TriggerType
        {
            get => triggerType;
            set => triggerType = value;
        }

        private bool hasTriggered = false;

        void OnTriggerEnter(Collider other)
        {
            if (hasTriggered) return;

            if (other.CompareTag("Player"))
            {
                hasTriggered = true;

                // Quick-Quiz ausloesen
                if (QuizManager.Instance != null)
                {
                    QuizManager.Instance.ShowQuickQuestion(triggerType);
                }

                Debug.Log($"Quiz-Trigger ausgeloest: {triggerType}");
            }
        }

        void OnTriggerExit(Collider other)
        {
            // Reset fuer naechsten Durchlauf (falls Objekt recycelt wird)
            if (other.CompareTag("Player"))
            {
                // Optional: Trigger nach kurzer Zeit wieder aktivieren
                // hasTriggered = false;
            }
        }

        // Wird aufgerufen wenn Objekt recycelt wird
        void OnDisable()
        {
            hasTriggered = false;
        }
    }
}
